# Generated by Django 4.0.4 on 2022-04-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageupload', models.ImageField(upload_to='media')),
                ('Title_of_card', models.CharField(max_length=30)),
                ('link_of_the_card', models.TextField(max_length=100)),
                ('commment', models.CharField(max_length=500)),
            ],
        ),
    ]
