# Generated by Django 4.0.4 on 2022-04-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=25)),
                ('LastName', models.CharField(max_length=25)),
                ('Email', models.EmailField(max_length=100)),
                ('Message', models.TextField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='cards',
            name='link_of_the_card',
        ),
        migrations.AddField(
            model_name='cards',
            name='github_link',
            field=models.CharField(default='https://github.com/hassanyange/yangeshop.git', max_length=30),
        ),
        migrations.AddField(
            model_name='cards',
            name='heroku_link',
            field=models.CharField(default='https://dashboard.heroku.com/apps/yange-portifolio-project', max_length=30),
        ),
        migrations.AlterField(
            model_name='cards',
            name='commment',
            field=models.CharField(default='small explanations', max_length=100),
        ),
    ]
